blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/sidharthmohannair/Fury-Drone-Project/issues/new?template=bug_report.md
    about: Report a bug or unexpected behavior.
  - name: Feature Request
    url: https://github.com/sidharthmohannair/Fury-Drone-Project/issues/new?template=feature_request.md
    about: Suggest a new feature or enhancement.

