name: Issue Template
description: Use this template to report bugs, request features, or suggest improvements.
title: "[ISSUE] - "
labels: ["triage"]
assignees: ""
---

### Issue Type

Please select one of the following options:

- [ ] Bug Report 🐞
- [ ] Feature Request ✨
- [ ] Documentation Improvement 📚

---

### Description

**Provide a detailed description of the issue or request:**

---

### Steps to Reproduce (for bugs only)

1. **What steps caused the problem?**
2. **What did you expect to happen?**
3. **What actually happened?**

---

### Feature Request (for feature requests only)

1. **What functionality or improvement are you requesting?**
2. **Why is this feature important?**

---

### Suggested Solution/Workaround

- **If you have a solution or workaround, please describe it.**

---

### Supporting Information

1. **Drone Version:** (e.g., FuryVision AAV v2)
2. **System Details:** (e.g., OS, dependencies, Mission Planner version)
3. **Relevant Files/Logs:** Attach screenshots, test logs, or error messages, if applicable.

---

### Checklist

Before submitting, please ensure you’ve done the following:

- [ ] Checked the existing issues to avoid duplicates.
- [ ] Provided all necessary information.
- [ ] Included relevant files or logs, if needed.

---

### Additional Context

**Add any other details that would help resolve the issue.**
